# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node_CI

on:
  pull_request:
    branches: [ "deploy" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./eco-location
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.2
      with:
        node-version: lts/Hydrogen
        
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install
      working-directory: ${{ env.working-directory }}

    - name: Build
      run: CI=false npm run build
      working-directory: ${{ env.working-directory }}
